name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
      - maint/publish_to_private_pypi

env:
  MAIN_PYTHON_VERSION: '3.9'
  PACKAGE_NAME: 'ansys-api-tools-filetransfer'

jobs:
  build-library:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  release-pypi-private:
    name: "Release to private PyPI"
    runs-on: ubuntu-latest
    needs: [build-library]
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref == 'refs/heads/maint/publish_to_private_pypi'
    steps:
      - name: "Release to the private PyPI repository"
        uses: ansys/actions/release-pypi-private@fix/conditional-skip-release
        with:
          library-name:  ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
          skip-existing: false
