name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.9'
  PACKAGE_NAME: 'ansys-api-tools-filetransfer'

jobs:
  build-library:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
      - name: "Install pre-commit"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: "Run pre-commit"
        run: |
          pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  check-version:
    name: "Check version is bumped"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Check version is changed"
        run: |
          git fetch origin $BASE_BRANCH

          NUM_CHARS=$(git diff --ignore-all-space origin/$BASE_BRANCH -- src/ansys/api/tools/filetransfer/VERSION | wc -c)

          if [ $NUM_CHARS -eq 0 ]; then
            echo "Version is not bumped.  Please update the version in src/ansys/api/tools/filetransfer/VERSION"
            exit 1
          fi
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}


  release-pypi-private:
    name: "Release to private PyPI"
    runs-on: ubuntu-latest
    needs: [build-library]
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref == 'refs/heads/main'
    steps:
      - name: "Release to the private PyPI repository"
        uses: ansys/actions/release-pypi-private@v4
        with:
          library-name:  ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
